### ISSUE TITLE
Switch to stdlib venv instead of virtualenv?

### ISSUE THREAD

**Issue by anntzer** [sollidsnake/pipman#1]
I'm not sure you need the 3rd-party virtualenv as a dependency.

**Comment by sollidsnake** [comment]
For some reason, when I use the `venv` module, it generates the virtualenv with an old version of pip (6.0.8 instead of 7.1.0), that doesn't provide some important info. Do you have a clue of why that happens?

**Comment by anntzer** [comment]
I observe the same; I guess you can start by running `pip install -U pip` after creating the venv.

**Comment by sollidsnake** [comment]
I was a little reluctant to do that, because it didn't feel right. But I think you're right. It's done on commit 27669e274a. I also removed the `python-virtualenv` dependency from the pkgbuild. Thanks for the help.
