### ISSUE TITLE
Updating installed packages

### ISSUE THREAD

**Issue by n3f4s** [sollidsnake/pipman#10]
Hi,
It would be nice to have an option to update all the packages installed by ``pipman``.

I did a bit of research about how to implement an update command.

From what I found, there is no way, in the ``PKGBUILD``, to tell ``pacman`` what to do to update the packages (not installed by ``pacman``).

I tried to have a look at ``pyalpm`` (which is a python binding to ``alpm``, the library to interact with ``arch`` package database), but I found little to  no documentation (except for a python re-implementation of ``pacman``) and I'm not even sure that it will be useful.

An other solution is to have a database for ``pipman`` (SQL, noSQL or a text file). To update the installed packages, ``pipman`` would re-install (like ``yaourt`` and ``pacaur`` are doing for *AUR*) all of the packages in the database.

What do you think is the best option for implementing the update command ?

**Comment by sollidsnake** [comment]
First of all, apologies for taking so long to answer. I've been very busy these days.

Being able to update packages is a goal of this project, but I haven't worked this issue yet. Currently, pipman only generates the PKGBUILD, and doesn't actually track anything. I'd like to avoid databases and keep this simplicity if possible.

I'm thinking in adding `pipman-package` as an identifier in pacman's group or maybe pacman's provider, and when the update command is invoked, pipman would search for all the packages with this identifier and update them. Do you think would be a good approach?

**Comment by n3f4s** [comment]
I have little to no idea how pacman's database work. I tried to read pacman's python implementation but I didn't have time (but I'm planning to read it).
Won't pacman try to update everything in his database when doing an update ?
If not, your approach is (IMHO) the best.

I've tried to read _pacaur_ and _yaourt_ source code to see how they do the update but they are written in bash and the code his quite hard to read.

**Comment by sollidsnake** [comment]
Pacman, yaourt and pacaur use their own database of packages. To update a package, they compare the name and version of a package with your local one -- if the name matches and the repository version is greater than the installed one, it updates.

Pipman has nothing to do with those repositories. It only generates a package that is installed locally only with pacman. That package will only update through pacman (or yaourt) if a package with the same name and greater version was added to the repository.

I'll look further into this approach I mentioned and see if it works.

**Comment by n3f4s** [comment]
I think I misunderstood your idea the first time. Lets see if I understood it right this time.

The idea would be, when creating the ``PKGBUILD`` to add ``pipman-package`` in a field. When updating ``pipman`` will list the packages that have ``pipman-package`` in this field and check (with pip) if they need to be updated (and update the package by re-installing it if needed).

Have I understood your idea ?

If yes, it's a good idea. It shouldn't be too hard to implement.

**Comment by sollidsnake** [comment]
Yes, it's how you described. Although I'm not sure if this approach goes against pacman's guidelines, I think it's the best one. I'll go on with it.

**Comment by sollidsnake** [comment]
This feature was implemented on the latest commit. Now you can update the packages installed through pipman with `pipman -Su`. Note that this will only work for new packages installed using the new version, your old packages won't be updated. Please let me know if you find any issue.
