### ISSUE TITLE
AUR package missing dependency

### ISSUE THREAD

**Issue by alerque** [sollidsnake/pipman#17]
The AUR package for _this project_ is missing a dependency. Maybe this is overlooked by people living in the python ecosystem anyway, but it doesn't seem to run without python-virtualenv installed.

**Comment by sollidsnake** [comment]
I tried running pipman without python-virtualenv and it worked without issues. Are you using the latest version? If yes, what command you are running and what error message do you get?

**Comment by alerque** [comment]
I'm now unable to duplicate this on a clean system. I suspect my original problem had to do with network problems at the "Peparing virtualenv" stage.
