### ISSUE TITLE
Generate code that includes a LICENSE file

### ISSUE THREAD

**Issue by anntzer** [sollidsnake/pipman#2]
Add a line such as

```
install -D -m644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
```

to `package()`.

**Comment by sollidsnake** [comment]
Packages downloaded using pip don't seem to include a LICENSE file. Instead, I use `pip show package` that shows the license name (GPL, MIT, BSD...) and add it to the PKGBUILD. Please reopen this if you know an appropriate way of getting the license or if you still think this should have another solution.

**Comment by anntzer** [comment]
I see the issue: pip uses the wheel if available, which doesn't usually include the licence file, whereas "traditional" hand-written PKGBUILDs tend to use the tgz, which usually contains one.  Technically, Arch Packaging standards mention that each MIT/BSD licensed package should have its own license file, probably because the file actually contains the name of the license owner, so in theory you can't just create it just knowing the output of `pip show package`.  Oh well.
