### ISSUE TITLE
merge (my fork) into upstream

### ISSUE THREAD

**Issue by n3f4s** [sollidsnake/pipman#4]
Hi,
some times ago, I forked your repository to correct an error in the generated PKGBUILD.
Since the fork, I made other modifications and improvement: 
- I refactor part of the code:
  - removed the class to use "free" functions (I found the class too rigid for adding features)
  - split function into separate file/module
  - extract PKGBUILD template in it's own file
- I changed the (normal) output format to be like pacman output
- I switch command line argument parsing from python standard lib to docopt
- I intend to change the command line argument to look like pacman command line argument
- I added a search function
- I add auto-installation (Work In Progress)
  (that should be every modification I have made)

I was thinking that it may be better to merge my fork into your repository.
What do you think of it ? Would it be OK ?

**Comment by sollidsnake** [comment]
Wow. That's a lot of changes. Thanks for taking your time and reporting it!
I'm very busy these days but I'll try to look into it and merge as soon as possible.

**Comment by n3f4s** [comment]
At the beginning I was planning to make only few changes but I went a little overboard. I hadn't the reflexes to submit a pull request with the first change and I must admit that my (commit) history may be messy. I'm not used to contribute to open source project.
Don't hesitate to refuse to merge if it's too much work.

**Comment by sollidsnake** [comment]
I didn't mean it's bad that it's a big merge. It was a comment :)

**Comment by sollidsnake** [comment]
I looked at the changes you made and they look awesome! I'll certainly merge them and credit you for them. I pushed them into a new branch called `bigupdate` where I'll do some changes doing the merge, because there are few issues I saw that need to be fixed:
- All files have permission to be executed. Only `src/pipman/pipman.py` should have it.
- Debug output is displayed twice:

```
$ ./pipman search potato
>>> debug: Creating venv in /tmp/pipman/pipman-venv <<<
>>> debug: Creating venv in /tmp/pipman/pipman-venv <<<
>>> debug: List of packages : ['potato'] <<<
>>> debug: List of packages : ['potato'] <<<
>>> debug: pip search potato <<<
>>> debug: pip search potato <<<
```
- The sintax `pipman install package --no-install` looks a bit strange. Maybe installing and generating should be different commands, like `pipman generate` and `pipman install`. Or using the previous syntax, with the flag --install to actually install it: `pipman package --install`.

I'll keep this issue open until the changes are merged into master. Thanks again!

**Comment by n3f4s** [comment]
- For the permissions, I didn't give a thought to it...
- For the debug output, I tried to fix this issue for less than 10 minutes than I gave up, it didn't bothered me since it's debug output and it should be turned of in the release.
- I find the `--install` option strange. I (as a user) expect this kind of tool to install (by default) the package (like `pacgem` do for _ruby gems_), or to have an `install` (like, `pip`, `gem`, ...) command. So, IMHO, the `generate`/`install` commands is the better option.

**Comment by sollidsnake** [comment]
I just pushed some updates on the bigupdate branch. Could test if everything works for you? Then I'll merge it into master.

**Comment by n3f4s** [comment]
seems to works. I tried `pipman pysixel` and it works (I didn't try to install the generated PKGBUILD but it seemed OK). Is there something else to test (automated testing would be nice ^^) ?
Where is this version compared to my fork (I've noticed that there is no commands) ?

**Comment by sollidsnake** [comment]
Yes I should have already done the unit tests from the start. I'll write them as soon as possible. 

This version is basically yours with a few fixes and refactoration. I'll merge it later today and put a credit section in the todo with a thanks to you.

**Comment by sollidsnake** [comment]
Sorry, I'm gonna have to step back on this. I'm finding your code structure more complex to maintain than the previous. I believe it will be better to reimplement your features in the previous code structure.

Anyway, thanks for your help and work. I really appreciate it. I'll close this issue once everything is implemented.

**Comment by n3f4s** [comment]
no problem, ask if there is any problem with my code.

**Comment by sollidsnake** [comment]
I just pushed the highlight functionality with pipman search, and I believe we covered all the features discussed here. Please open another issue if you think some feature of this issue is still missing.
