### ISSUE TITLE
PKGBUILD.tpl (template) is not bundled into package.

### ISSUE THREAD

**Issue by oysteijo** [sollidsnake/pipman#7]
`[oystein@jupiter xlsxwriter]$ pipman --no-install install xlsxwriter
[...]
    write_pkgbuild(package)
  File "/usr/lib/python3.5/site-packages/pipman/printer.py", line 70, in write_pkgbuild
    file_.write(generate_pkgbuild(package))
  File "/usr/lib/python3.5/site-packages/pipman/printer.py", line 31, in generate_pkgbuild
    with open(TPL_FILE) as file_:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/pipman/PKGBUILD.tpl'`

(I solved this by copying in the file manually in pkgdir and repack.)

**Comment by sollidsnake** [comment]
Thanks for taking your time to report. It working by now.
I ended up downgrading to an older version. I'll reimplement the new features soon.

Please reopen this issue if the problem still happens for you.
